stages:
  - build

build:
  stage: build
  needs: []
  tags:
    - panel_tests
  image: maven:3-eclipse-temurin-8
  before_script:
    - mvn clean
  script:
    - mvn install
    - java -jar target/ForgeServerJAR.jar
    - cp target/ForgeServerJAR.jar target/server.jar
    - /usr/bin/mc cp target/server.jar sparked-modpacks/server.jar
